 version: '3.3'
 services:

   mqfull:
     image: {dtr-registry-address}/admin/test-mq:1.0
     environment:
       LICENSE: accept
       MQ_QMGR_NAME: QM1
     # MQSNOAUT - This environment variable disables all authorization checking in MQ. 
     # This is not recommended for production environments
       MQSNOAUT: "yes"
     ports:
       - "1414:1414"
       - "33443:9443"
   sender:
     image: {dtr-registry-address}/admin/test-sender:1.0
     ports:
       - "34090:9080"
       - "34443:9443"
   receiver:
     image: {dtr-registry-address}/admin/test-receiver:1.0
     ports:
       - "34081:9080"
       - "34444:9443"
